[package]
name = "tenet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.1", features = ["derive"] }
git2 = "0.17.0"
serial_test = "2.0.0"
tempfile = "3.5.0"
